services:
  app:
    image: mertdalbudak/paper-mc:latest
    ports:
      - 25565:25565
    volumes:
      - /home/mert/server:/app/server
      - /home/mert/backup:/app/backups
    environment:
      - Xms=1G
      - Xmx=3G