name: Docker Image CI

on:
  push:
    branches: [ "docker-ci/cd" ]
  pull_request:
    branches: [ "docker-ci/cd" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
        name: Checkout
        uses: actions/checkout@v4
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
    - 
      name: Docker Buildx Bake
      uses: docker/bake-action@v5.3.0
      id: buildx
      with:
          source: "${{ github.server_url }}/${{ github.repository }}.git#${{ github.ref }}"
    -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
        name: Build
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          #platforms: linux/amd64,linux/arm64
          push: false
          tags: mertdalbudak/paper-mc:test
