name: Docker Image CI

on:
  push:
    branches: [ "docker-ci/cd" ]
  pull_request:
    branches: [ "docker-ci/cd" ]

jobs:

  build:

    runs-on: alpine

    steps:
    -
        name: Checkout
        uses: actions/checkout@v4
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
    - 
      name: Docker Buildx Bake
      uses: docker/bake-action@v5.3.0
      with:
          source: "${{ github.server_url }}/${{ github.repository }}.git#${{ github.ref }}"
          platforms: linux/amd64,linux/arm64
